import dataclasses

# 登録更新用のデータクラス定義
@dataclasses.dataclass
class Assessment:
    ases_year: str
    ases_month: str
    id: int
    lv: str
    comment: str
    ases_a1: str
    ases_a2: str
    ases_a3: str
    ases_a4: str
    ases_a5: str
    ases_a6: str
    ases_a7: str
    ases_a8: str
    ases_b1: str
    ases_b2: str
    ases_b3: str
    ases_b4: str
    ases_b5: str
    ases_b6: str
    ases_b7: str
    ases_b8: str
    ases_c1: str
    ases_c2: str
    ases_c3: str
    ases_c4: str
    ases_c5: str
    ases_c6: str
    ases_c7: str
    ases_c8: str
    ases_d1: str
    ases_d2: str
    ases_d3: str
    ases_d4: str
    ases_d5: str
    ases_d6: str
    ases_d7: str
    ases_d8: str
    ases_e1: str
    ases_e2: str
    ases_e3: str
    ases_e4: str
    ases_e5: str
    ases_e6: str
    ases_e7: str
    ases_e8: str